//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1008 版自动生成。
// 
#pragma warning disable 1591

namespace DianChe.DianCheWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ItemClickServiceSoap", Namespace="http://tempuri.org/")]
    public partial class ItemClickService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private MySoapHeader mySoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsExistUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsExistMacOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddMyItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditMyItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteMyItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback DispatchItemClickOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveAliveOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddMsgOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMsgOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMsgStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetItemOnlineOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetItemTaskFromJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetItemRankFromJsonOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ItemClickService() {
            this.Url = global::DianChe.Properties.Settings.Default.DianChe_DianCheWebService_ItemClickService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public MySoapHeader MySoapHeaderValue {
            get {
                return this.mySoapHeaderValueField;
            }
            set {
                this.mySoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event IsExistUserCompletedEventHandler IsExistUserCompleted;
        
        /// <remarks/>
        public event IsExistMacCompletedEventHandler IsExistMacCompleted;
        
        /// <remarks/>
        public event RegUserCompletedEventHandler RegUserCompleted;
        
        /// <remarks/>
        public event UserLoginCompletedEventHandler UserLoginCompleted;
        
        /// <remarks/>
        public event AddMyItemCompletedEventHandler AddMyItemCompleted;
        
        /// <remarks/>
        public event EditMyItemCompletedEventHandler EditMyItemCompleted;
        
        /// <remarks/>
        public event DeleteMyItemCompletedEventHandler DeleteMyItemCompleted;
        
        /// <remarks/>
        public event DispatchItemClickCompletedEventHandler DispatchItemClickCompleted;
        
        /// <remarks/>
        public event SaveAliveCompletedEventHandler SaveAliveCompleted;
        
        /// <remarks/>
        public event AddMsgCompletedEventHandler AddMsgCompleted;
        
        /// <remarks/>
        public event GetMsgCompletedEventHandler GetMsgCompleted;
        
        /// <remarks/>
        public event UpdateMsgStatusCompletedEventHandler UpdateMsgStatusCompleted;
        
        /// <remarks/>
        public event GetItemOnlineCompletedEventHandler GetItemOnlineCompleted;
        
        /// <remarks/>
        public event GetItemTaskFromJsonCompletedEventHandler GetItemTaskFromJsonCompleted;
        
        /// <remarks/>
        public event GetItemRankFromJsonCompletedEventHandler GetItemRankFromJsonCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsExistUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsExistUser(string user_name) {
            object[] results = this.Invoke("IsExistUser", new object[] {
                        user_name});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsExistUserAsync(string user_name) {
            this.IsExistUserAsync(user_name, null);
        }
        
        /// <remarks/>
        public void IsExistUserAsync(string user_name, object userState) {
            if ((this.IsExistUserOperationCompleted == null)) {
                this.IsExistUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsExistUserOperationCompleted);
            }
            this.InvokeAsync("IsExistUser", new object[] {
                        user_name}, this.IsExistUserOperationCompleted, userState);
        }
        
        private void OnIsExistUserOperationCompleted(object arg) {
            if ((this.IsExistUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsExistUserCompleted(this, new IsExistUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsExistMac", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsExistMac(string mac_address) {
            object[] results = this.Invoke("IsExistMac", new object[] {
                        mac_address});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsExistMacAsync(string mac_address) {
            this.IsExistMacAsync(mac_address, null);
        }
        
        /// <remarks/>
        public void IsExistMacAsync(string mac_address, object userState) {
            if ((this.IsExistMacOperationCompleted == null)) {
                this.IsExistMacOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsExistMacOperationCompleted);
            }
            this.InvokeAsync("IsExistMac", new object[] {
                        mac_address}, this.IsExistMacOperationCompleted, userState);
        }
        
        private void OnIsExistMacOperationCompleted(object arg) {
            if ((this.IsExistMacCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsExistMacCompleted(this, new IsExistMacCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EntityUser RegUser(string user_name, string pwd, string phone, string email, string mac_address, string cpu, string mem, string os) {
            object[] results = this.Invoke("RegUser", new object[] {
                        user_name,
                        pwd,
                        phone,
                        email,
                        mac_address,
                        cpu,
                        mem,
                        os});
            return ((EntityUser)(results[0]));
        }
        
        /// <remarks/>
        public void RegUserAsync(string user_name, string pwd, string phone, string email, string mac_address, string cpu, string mem, string os) {
            this.RegUserAsync(user_name, pwd, phone, email, mac_address, cpu, mem, os, null);
        }
        
        /// <remarks/>
        public void RegUserAsync(string user_name, string pwd, string phone, string email, string mac_address, string cpu, string mem, string os, object userState) {
            if ((this.RegUserOperationCompleted == null)) {
                this.RegUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegUserOperationCompleted);
            }
            this.InvokeAsync("RegUser", new object[] {
                        user_name,
                        pwd,
                        phone,
                        email,
                        mac_address,
                        cpu,
                        mem,
                        os}, this.RegUserOperationCompleted, userState);
        }
        
        private void OnRegUserOperationCompleted(object arg) {
            if ((this.RegUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegUserCompleted(this, new RegUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UserLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EntityUser UserLogin(string user_name, string pwd, string cpu, string mem, string os) {
            object[] results = this.Invoke("UserLogin", new object[] {
                        user_name,
                        pwd,
                        cpu,
                        mem,
                        os});
            return ((EntityUser)(results[0]));
        }
        
        /// <remarks/>
        public void UserLoginAsync(string user_name, string pwd, string cpu, string mem, string os) {
            this.UserLoginAsync(user_name, pwd, cpu, mem, os, null);
        }
        
        /// <remarks/>
        public void UserLoginAsync(string user_name, string pwd, string cpu, string mem, string os, object userState) {
            if ((this.UserLoginOperationCompleted == null)) {
                this.UserLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserLoginOperationCompleted);
            }
            this.InvokeAsync("UserLogin", new object[] {
                        user_name,
                        pwd,
                        cpu,
                        mem,
                        os}, this.UserLoginOperationCompleted, userState);
        }
        
        private void OnUserLoginOperationCompleted(object arg) {
            if ((this.UserLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserLoginCompleted(this, new UserLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddMyItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddMyItem(EntityItemTask model) {
            object[] results = this.Invoke("AddMyItem", new object[] {
                        model});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddMyItemAsync(EntityItemTask model) {
            this.AddMyItemAsync(model, null);
        }
        
        /// <remarks/>
        public void AddMyItemAsync(EntityItemTask model, object userState) {
            if ((this.AddMyItemOperationCompleted == null)) {
                this.AddMyItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddMyItemOperationCompleted);
            }
            this.InvokeAsync("AddMyItem", new object[] {
                        model}, this.AddMyItemOperationCompleted, userState);
        }
        
        private void OnAddMyItemOperationCompleted(object arg) {
            if ((this.AddMyItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddMyItemCompleted(this, new AddMyItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EditMyItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EditMyItem(EntityItemTask model) {
            object[] results = this.Invoke("EditMyItem", new object[] {
                        model});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EditMyItemAsync(EntityItemTask model) {
            this.EditMyItemAsync(model, null);
        }
        
        /// <remarks/>
        public void EditMyItemAsync(EntityItemTask model, object userState) {
            if ((this.EditMyItemOperationCompleted == null)) {
                this.EditMyItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditMyItemOperationCompleted);
            }
            this.InvokeAsync("EditMyItem", new object[] {
                        model}, this.EditMyItemOperationCompleted, userState);
        }
        
        private void OnEditMyItemOperationCompleted(object arg) {
            if ((this.EditMyItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditMyItemCompleted(this, new EditMyItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteMyItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteMyItem(string local_item_task_id) {
            object[] results = this.Invoke("DeleteMyItem", new object[] {
                        local_item_task_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteMyItemAsync(string local_item_task_id) {
            this.DeleteMyItemAsync(local_item_task_id, null);
        }
        
        /// <remarks/>
        public void DeleteMyItemAsync(string local_item_task_id, object userState) {
            if ((this.DeleteMyItemOperationCompleted == null)) {
                this.DeleteMyItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteMyItemOperationCompleted);
            }
            this.InvokeAsync("DeleteMyItem", new object[] {
                        local_item_task_id}, this.DeleteMyItemOperationCompleted, userState);
        }
        
        private void OnDeleteMyItemOperationCompleted(object arg) {
            if ((this.DeleteMyItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteMyItemCompleted(this, new DeleteMyItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DispatchItemClick", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EntityItemClick[] DispatchItemClick(string mac_address) {
            object[] results = this.Invoke("DispatchItemClick", new object[] {
                        mac_address});
            return ((EntityItemClick[])(results[0]));
        }
        
        /// <remarks/>
        public void DispatchItemClickAsync(string mac_address) {
            this.DispatchItemClickAsync(mac_address, null);
        }
        
        /// <remarks/>
        public void DispatchItemClickAsync(string mac_address, object userState) {
            if ((this.DispatchItemClickOperationCompleted == null)) {
                this.DispatchItemClickOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDispatchItemClickOperationCompleted);
            }
            this.InvokeAsync("DispatchItemClick", new object[] {
                        mac_address}, this.DispatchItemClickOperationCompleted, userState);
        }
        
        private void OnDispatchItemClickOperationCompleted(object arg) {
            if ((this.DispatchItemClickCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DispatchItemClickCompleted(this, new DispatchItemClickCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveAlive", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SaveAlive(string mac_address) {
            this.Invoke("SaveAlive", new object[] {
                        mac_address});
        }
        
        /// <remarks/>
        public void SaveAliveAsync(string mac_address) {
            this.SaveAliveAsync(mac_address, null);
        }
        
        /// <remarks/>
        public void SaveAliveAsync(string mac_address, object userState) {
            if ((this.SaveAliveOperationCompleted == null)) {
                this.SaveAliveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveAliveOperationCompleted);
            }
            this.InvokeAsync("SaveAlive", new object[] {
                        mac_address}, this.SaveAliveOperationCompleted, userState);
        }
        
        private void OnSaveAliveOperationCompleted(object arg) {
            if ((this.SaveAliveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveAliveCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddMsg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddMsg(string msg_from, string msg_to, string msg_subject, string msg_content, string msg_type) {
            this.Invoke("AddMsg", new object[] {
                        msg_from,
                        msg_to,
                        msg_subject,
                        msg_content,
                        msg_type});
        }
        
        /// <remarks/>
        public void AddMsgAsync(string msg_from, string msg_to, string msg_subject, string msg_content, string msg_type) {
            this.AddMsgAsync(msg_from, msg_to, msg_subject, msg_content, msg_type, null);
        }
        
        /// <remarks/>
        public void AddMsgAsync(string msg_from, string msg_to, string msg_subject, string msg_content, string msg_type, object userState) {
            if ((this.AddMsgOperationCompleted == null)) {
                this.AddMsgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddMsgOperationCompleted);
            }
            this.InvokeAsync("AddMsg", new object[] {
                        msg_from,
                        msg_to,
                        msg_subject,
                        msg_content,
                        msg_type}, this.AddMsgOperationCompleted, userState);
        }
        
        private void OnAddMsgOperationCompleted(object arg) {
            if ((this.AddMsgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddMsgCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMsg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EntityMsg[] GetMsg(string msg_type) {
            object[] results = this.Invoke("GetMsg", new object[] {
                        msg_type});
            return ((EntityMsg[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMsgAsync(string msg_type) {
            this.GetMsgAsync(msg_type, null);
        }
        
        /// <remarks/>
        public void GetMsgAsync(string msg_type, object userState) {
            if ((this.GetMsgOperationCompleted == null)) {
                this.GetMsgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMsgOperationCompleted);
            }
            this.InvokeAsync("GetMsg", new object[] {
                        msg_type}, this.GetMsgOperationCompleted, userState);
        }
        
        private void OnGetMsgOperationCompleted(object arg) {
            if ((this.GetMsgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMsgCompleted(this, new GetMsgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateMsgStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMsgStatus(long local_msg_id, int send_status) {
            this.Invoke("UpdateMsgStatus", new object[] {
                        local_msg_id,
                        send_status});
        }
        
        /// <remarks/>
        public void UpdateMsgStatusAsync(long local_msg_id, int send_status) {
            this.UpdateMsgStatusAsync(local_msg_id, send_status, null);
        }
        
        /// <remarks/>
        public void UpdateMsgStatusAsync(long local_msg_id, int send_status, object userState) {
            if ((this.UpdateMsgStatusOperationCompleted == null)) {
                this.UpdateMsgStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMsgStatusOperationCompleted);
            }
            this.InvokeAsync("UpdateMsgStatus", new object[] {
                        local_msg_id,
                        send_status}, this.UpdateMsgStatusOperationCompleted, userState);
        }
        
        private void OnUpdateMsgStatusOperationCompleted(object arg) {
            if ((this.UpdateMsgStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMsgStatusCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetItemOnline", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetItemOnline(long item_id) {
            object[] results = this.Invoke("GetItemOnline", new object[] {
                        item_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetItemOnlineAsync(long item_id) {
            this.GetItemOnlineAsync(item_id, null);
        }
        
        /// <remarks/>
        public void GetItemOnlineAsync(long item_id, object userState) {
            if ((this.GetItemOnlineOperationCompleted == null)) {
                this.GetItemOnlineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemOnlineOperationCompleted);
            }
            this.InvokeAsync("GetItemOnline", new object[] {
                        item_id}, this.GetItemOnlineOperationCompleted, userState);
        }
        
        private void OnGetItemOnlineOperationCompleted(object arg) {
            if ((this.GetItemOnlineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemOnlineCompleted(this, new GetItemOnlineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetItemTaskFromJson", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EntityItemTask GetItemTaskFromJson(string jsonItem) {
            object[] results = this.Invoke("GetItemTaskFromJson", new object[] {
                        jsonItem});
            return ((EntityItemTask)(results[0]));
        }
        
        /// <remarks/>
        public void GetItemTaskFromJsonAsync(string jsonItem) {
            this.GetItemTaskFromJsonAsync(jsonItem, null);
        }
        
        /// <remarks/>
        public void GetItemTaskFromJsonAsync(string jsonItem, object userState) {
            if ((this.GetItemTaskFromJsonOperationCompleted == null)) {
                this.GetItemTaskFromJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemTaskFromJsonOperationCompleted);
            }
            this.InvokeAsync("GetItemTaskFromJson", new object[] {
                        jsonItem}, this.GetItemTaskFromJsonOperationCompleted, userState);
        }
        
        private void OnGetItemTaskFromJsonOperationCompleted(object arg) {
            if ((this.GetItemTaskFromJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemTaskFromJsonCompleted(this, new GetItemTaskFromJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetItemRankFromJson", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EntityItemRank GetItemRankFromJson(string jsonItem) {
            object[] results = this.Invoke("GetItemRankFromJson", new object[] {
                        jsonItem});
            return ((EntityItemRank)(results[0]));
        }
        
        /// <remarks/>
        public void GetItemRankFromJsonAsync(string jsonItem) {
            this.GetItemRankFromJsonAsync(jsonItem, null);
        }
        
        /// <remarks/>
        public void GetItemRankFromJsonAsync(string jsonItem, object userState) {
            if ((this.GetItemRankFromJsonOperationCompleted == null)) {
                this.GetItemRankFromJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemRankFromJsonOperationCompleted);
            }
            this.InvokeAsync("GetItemRankFromJson", new object[] {
                        jsonItem}, this.GetItemRankFromJsonOperationCompleted, userState);
        }
        
        private void OnGetItemRankFromJsonOperationCompleted(object arg) {
            if ((this.GetItemRankFromJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemRankFromJsonCompleted(this, new GetItemRankFromJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class MySoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passWordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string PassWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityItemRank {
        
        private System.Guid local_item_rank_idField;
        
        private string nickField;
        
        private long item_idField;
        
        private string item_titleField;
        
        private string img_urlField;
        
        private byte[] img_dataField;
        
        private decimal priceField;
        
        private string creative_one_titleField;
        
        private string creative_two_titleField;
        
        private string keywordField;
        
        private int current_nature_rankField;
        
        private int lowest_nature_rankField;
        
        private int highest_nature_rankField;
        
        private int current_ztc_rankField;
        
        private int lowest_ztc_rankField;
        
        private int highest_ztc_rankField;
        
        private System.DateTime create_timeField;
        
        private System.DateTime update_timeField;
        
        private string remarkField;
        
        private bool is_sms_notifyField;
        
        private bool is_mail_notifyField;
        
        private bool is_enableField;
        
        private bool is_complete_searchField;
        
        private bool is_delete_by_userField;
        
        /// <remarks/>
        public System.Guid local_item_rank_id {
            get {
                return this.local_item_rank_idField;
            }
            set {
                this.local_item_rank_idField = value;
            }
        }
        
        /// <remarks/>
        public string nick {
            get {
                return this.nickField;
            }
            set {
                this.nickField = value;
            }
        }
        
        /// <remarks/>
        public long item_id {
            get {
                return this.item_idField;
            }
            set {
                this.item_idField = value;
            }
        }
        
        /// <remarks/>
        public string item_title {
            get {
                return this.item_titleField;
            }
            set {
                this.item_titleField = value;
            }
        }
        
        /// <remarks/>
        public string img_url {
            get {
                return this.img_urlField;
            }
            set {
                this.img_urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] img_data {
            get {
                return this.img_dataField;
            }
            set {
                this.img_dataField = value;
            }
        }
        
        /// <remarks/>
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string creative_one_title {
            get {
                return this.creative_one_titleField;
            }
            set {
                this.creative_one_titleField = value;
            }
        }
        
        /// <remarks/>
        public string creative_two_title {
            get {
                return this.creative_two_titleField;
            }
            set {
                this.creative_two_titleField = value;
            }
        }
        
        /// <remarks/>
        public string keyword {
            get {
                return this.keywordField;
            }
            set {
                this.keywordField = value;
            }
        }
        
        /// <remarks/>
        public int current_nature_rank {
            get {
                return this.current_nature_rankField;
            }
            set {
                this.current_nature_rankField = value;
            }
        }
        
        /// <remarks/>
        public int lowest_nature_rank {
            get {
                return this.lowest_nature_rankField;
            }
            set {
                this.lowest_nature_rankField = value;
            }
        }
        
        /// <remarks/>
        public int highest_nature_rank {
            get {
                return this.highest_nature_rankField;
            }
            set {
                this.highest_nature_rankField = value;
            }
        }
        
        /// <remarks/>
        public int current_ztc_rank {
            get {
                return this.current_ztc_rankField;
            }
            set {
                this.current_ztc_rankField = value;
            }
        }
        
        /// <remarks/>
        public int lowest_ztc_rank {
            get {
                return this.lowest_ztc_rankField;
            }
            set {
                this.lowest_ztc_rankField = value;
            }
        }
        
        /// <remarks/>
        public int highest_ztc_rank {
            get {
                return this.highest_ztc_rankField;
            }
            set {
                this.highest_ztc_rankField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime create_time {
            get {
                return this.create_timeField;
            }
            set {
                this.create_timeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime update_time {
            get {
                return this.update_timeField;
            }
            set {
                this.update_timeField = value;
            }
        }
        
        /// <remarks/>
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        public bool is_sms_notify {
            get {
                return this.is_sms_notifyField;
            }
            set {
                this.is_sms_notifyField = value;
            }
        }
        
        /// <remarks/>
        public bool is_mail_notify {
            get {
                return this.is_mail_notifyField;
            }
            set {
                this.is_mail_notifyField = value;
            }
        }
        
        /// <remarks/>
        public bool is_enable {
            get {
                return this.is_enableField;
            }
            set {
                this.is_enableField = value;
            }
        }
        
        /// <remarks/>
        public bool is_complete_search {
            get {
                return this.is_complete_searchField;
            }
            set {
                this.is_complete_searchField = value;
            }
        }
        
        /// <remarks/>
        public bool is_delete_by_user {
            get {
                return this.is_delete_by_userField;
            }
            set {
                this.is_delete_by_userField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityMsg {
        
        private long local_msg_idField;
        
        private string msg_fromField;
        
        private string msg_toField;
        
        private string msg_subjectField;
        
        private string msg_typeField;
        
        private string msg_contentField;
        
        private string file_pathField;
        
        private int send_statusField;
        
        private System.DateTime create_timeField;
        
        private System.DateTime update_timeField;
        
        /// <remarks/>
        public long local_msg_id {
            get {
                return this.local_msg_idField;
            }
            set {
                this.local_msg_idField = value;
            }
        }
        
        /// <remarks/>
        public string msg_from {
            get {
                return this.msg_fromField;
            }
            set {
                this.msg_fromField = value;
            }
        }
        
        /// <remarks/>
        public string msg_to {
            get {
                return this.msg_toField;
            }
            set {
                this.msg_toField = value;
            }
        }
        
        /// <remarks/>
        public string msg_subject {
            get {
                return this.msg_subjectField;
            }
            set {
                this.msg_subjectField = value;
            }
        }
        
        /// <remarks/>
        public string msg_type {
            get {
                return this.msg_typeField;
            }
            set {
                this.msg_typeField = value;
            }
        }
        
        /// <remarks/>
        public string msg_content {
            get {
                return this.msg_contentField;
            }
            set {
                this.msg_contentField = value;
            }
        }
        
        /// <remarks/>
        public string file_path {
            get {
                return this.file_pathField;
            }
            set {
                this.file_pathField = value;
            }
        }
        
        /// <remarks/>
        public int send_status {
            get {
                return this.send_statusField;
            }
            set {
                this.send_statusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime create_time {
            get {
                return this.create_timeField;
            }
            set {
                this.create_timeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime update_time {
            get {
                return this.update_timeField;
            }
            set {
                this.update_timeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityItemClick {
        
        private long local_idField;
        
        private long item_idField;
        
        private System.Guid local_item_task_idField;
        
        private string mac_addressField;
        
        private string item_titleField;
        
        private string creative_one_titleField;
        
        private string creative_two_titleField;
        
        private string nickField;
        
        private string keywordField;
        
        private System.DateTime create_timeField;
        
        private System.DateTime update_timeField;
        
        private System.Nullable<bool> is_succeedField;
        
        /// <remarks/>
        public long local_id {
            get {
                return this.local_idField;
            }
            set {
                this.local_idField = value;
            }
        }
        
        /// <remarks/>
        public long item_id {
            get {
                return this.item_idField;
            }
            set {
                this.item_idField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid local_item_task_id {
            get {
                return this.local_item_task_idField;
            }
            set {
                this.local_item_task_idField = value;
            }
        }
        
        /// <remarks/>
        public string mac_address {
            get {
                return this.mac_addressField;
            }
            set {
                this.mac_addressField = value;
            }
        }
        
        /// <remarks/>
        public string item_title {
            get {
                return this.item_titleField;
            }
            set {
                this.item_titleField = value;
            }
        }
        
        /// <remarks/>
        public string creative_one_title {
            get {
                return this.creative_one_titleField;
            }
            set {
                this.creative_one_titleField = value;
            }
        }
        
        /// <remarks/>
        public string creative_two_title {
            get {
                return this.creative_two_titleField;
            }
            set {
                this.creative_two_titleField = value;
            }
        }
        
        /// <remarks/>
        public string nick {
            get {
                return this.nickField;
            }
            set {
                this.nickField = value;
            }
        }
        
        /// <remarks/>
        public string keyword {
            get {
                return this.keywordField;
            }
            set {
                this.keywordField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime create_time {
            get {
                return this.create_timeField;
            }
            set {
                this.create_timeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime update_time {
            get {
                return this.update_timeField;
            }
            set {
                this.update_timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> is_succeed {
            get {
                return this.is_succeedField;
            }
            set {
                this.is_succeedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityItemTask {
        
        private System.Guid local_item_task_idField;
        
        private string nickField;
        
        private long item_idField;
        
        private string item_titleField;
        
        private string img_urlField;
        
        private byte[] img_dataField;
        
        private decimal priceField;
        
        private string creative_one_titleField;
        
        private string creative_two_titleField;
        
        private string keywordField;
        
        private int max_clickField;
        
        private int run_daysField;
        
        private string effect_start_timeField;
        
        private string effect_end_timeField;
        
        private System.DateTime create_timeField;
        
        private System.DateTime update_timeField;
        
        private string remarkField;
        
        private bool is_enableField;
        
        /// <remarks/>
        public System.Guid local_item_task_id {
            get {
                return this.local_item_task_idField;
            }
            set {
                this.local_item_task_idField = value;
            }
        }
        
        /// <remarks/>
        public string nick {
            get {
                return this.nickField;
            }
            set {
                this.nickField = value;
            }
        }
        
        /// <remarks/>
        public long item_id {
            get {
                return this.item_idField;
            }
            set {
                this.item_idField = value;
            }
        }
        
        /// <remarks/>
        public string item_title {
            get {
                return this.item_titleField;
            }
            set {
                this.item_titleField = value;
            }
        }
        
        /// <remarks/>
        public string img_url {
            get {
                return this.img_urlField;
            }
            set {
                this.img_urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] img_data {
            get {
                return this.img_dataField;
            }
            set {
                this.img_dataField = value;
            }
        }
        
        /// <remarks/>
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string creative_one_title {
            get {
                return this.creative_one_titleField;
            }
            set {
                this.creative_one_titleField = value;
            }
        }
        
        /// <remarks/>
        public string creative_two_title {
            get {
                return this.creative_two_titleField;
            }
            set {
                this.creative_two_titleField = value;
            }
        }
        
        /// <remarks/>
        public string keyword {
            get {
                return this.keywordField;
            }
            set {
                this.keywordField = value;
            }
        }
        
        /// <remarks/>
        public int max_click {
            get {
                return this.max_clickField;
            }
            set {
                this.max_clickField = value;
            }
        }
        
        /// <remarks/>
        public int run_days {
            get {
                return this.run_daysField;
            }
            set {
                this.run_daysField = value;
            }
        }
        
        /// <remarks/>
        public string effect_start_time {
            get {
                return this.effect_start_timeField;
            }
            set {
                this.effect_start_timeField = value;
            }
        }
        
        /// <remarks/>
        public string effect_end_time {
            get {
                return this.effect_end_timeField;
            }
            set {
                this.effect_end_timeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime create_time {
            get {
                return this.create_timeField;
            }
            set {
                this.create_timeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime update_time {
            get {
                return this.update_timeField;
            }
            set {
                this.update_timeField = value;
            }
        }
        
        /// <remarks/>
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        public bool is_enable {
            get {
                return this.is_enableField;
            }
            set {
                this.is_enableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityUser {
        
        private int user_idField;
        
        private string user_nameField;
        
        private string pwdField;
        
        private string emailField;
        
        private string phoneField;
        
        private string mac_addressField;
        
        private string ip_addressField;
        
        private string cpuField;
        
        private string memField;
        
        private string osField;
        
        private int user_levelField;
        
        private System.DateTime start_dateField;
        
        private System.DateTime end_dateField;
        
        private System.DateTime create_timeField;
        
        private System.DateTime update_timeField;
        
        /// <remarks/>
        public int user_id {
            get {
                return this.user_idField;
            }
            set {
                this.user_idField = value;
            }
        }
        
        /// <remarks/>
        public string user_name {
            get {
                return this.user_nameField;
            }
            set {
                this.user_nameField = value;
            }
        }
        
        /// <remarks/>
        public string pwd {
            get {
                return this.pwdField;
            }
            set {
                this.pwdField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string mac_address {
            get {
                return this.mac_addressField;
            }
            set {
                this.mac_addressField = value;
            }
        }
        
        /// <remarks/>
        public string ip_address {
            get {
                return this.ip_addressField;
            }
            set {
                this.ip_addressField = value;
            }
        }
        
        /// <remarks/>
        public string cpu {
            get {
                return this.cpuField;
            }
            set {
                this.cpuField = value;
            }
        }
        
        /// <remarks/>
        public string mem {
            get {
                return this.memField;
            }
            set {
                this.memField = value;
            }
        }
        
        /// <remarks/>
        public string os {
            get {
                return this.osField;
            }
            set {
                this.osField = value;
            }
        }
        
        /// <remarks/>
        public int user_level {
            get {
                return this.user_levelField;
            }
            set {
                this.user_levelField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime start_date {
            get {
                return this.start_dateField;
            }
            set {
                this.start_dateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime end_date {
            get {
                return this.end_dateField;
            }
            set {
                this.end_dateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime create_time {
            get {
                return this.create_timeField;
            }
            set {
                this.create_timeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime update_time {
            get {
                return this.update_timeField;
            }
            set {
                this.update_timeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void IsExistUserCompletedEventHandler(object sender, IsExistUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsExistUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsExistUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void IsExistMacCompletedEventHandler(object sender, IsExistMacCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsExistMacCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsExistMacCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RegUserCompletedEventHandler(object sender, RegUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EntityUser Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EntityUser)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UserLoginCompletedEventHandler(object sender, UserLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EntityUser Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EntityUser)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddMyItemCompletedEventHandler(object sender, AddMyItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddMyItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddMyItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void EditMyItemCompletedEventHandler(object sender, EditMyItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditMyItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditMyItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeleteMyItemCompletedEventHandler(object sender, DeleteMyItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteMyItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteMyItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DispatchItemClickCompletedEventHandler(object sender, DispatchItemClickCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DispatchItemClickCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DispatchItemClickCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EntityItemClick[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EntityItemClick[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SaveAliveCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddMsgCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetMsgCompletedEventHandler(object sender, GetMsgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMsgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMsgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EntityMsg[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EntityMsg[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateMsgStatusCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetItemOnlineCompletedEventHandler(object sender, GetItemOnlineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemOnlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemOnlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetItemTaskFromJsonCompletedEventHandler(object sender, GetItemTaskFromJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemTaskFromJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemTaskFromJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EntityItemTask Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EntityItemTask)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetItemRankFromJsonCompletedEventHandler(object sender, GetItemRankFromJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemRankFromJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemRankFromJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EntityItemRank Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EntityItemRank)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591